[[achievements]]
name = "å°å°çŒ«"
emoji = "ðŸ˜¸"
description = "å‘é€æ¶ˆæ¯æ€»æ•°è¾¾åˆ° 100 æ¡"
type = ["send_message_count", ">=", "100"]

[[achievements]]
name = "æ‚¬æµ®çŒ«"
emoji = "ðŸ˜º"
description = "å‘é€æ¶ˆæ¯æ€»æ•°è¾¾åˆ° 300 æ¡"
type = ["send_message_count", ">=", "300"]

[[achievements]]
name = "çŒ«çŽ‹ï¼Ÿ"
emoji = "ðŸ˜¼"
description = "å‘é€æ¶ˆæ¯æ€»æ•°è¾¾åˆ° 500 æ¡"
type = ["send_message_count", ">=", "500"]

[[achievements]]
name = "å°å°çŒ« 2"
emoji = "ðŸ˜¸"
description = "å‘é€æ¶ˆæ¯æ€»æ•°è¾¾åˆ° 1000 æ¡"
type = ["send_message_count", ">=", "1000"]

[[achievements]]
name = "æ‚¬æµ®çŒ« 2"
emoji = "ðŸ˜º"
description = "å‘é€æ¶ˆæ¯æ€»æ•°è¾¾åˆ° 1500 æ¡"
type = ["send_message_count", ">=", "1500"]

[[achievements]]
name = "å›¾å§çŒ«"
emoji = "ðŸ–¼ï¸"
description = "å‘é€å›¾ç‰‡è¾¾åˆ° 50 å¼ "
type = ["send_image_count", ">=", "50"]

[[achievements]]
name = "è¡¨æƒ…çŒ«"
emoji = "ðŸŽ¨"
description = "å‘é€è´´çº¸è¾¾åˆ° 50 å¼ "
type = ["send_sticker_count", ">=", "50"]
