[[badges]]
name = "æ´»ç€å‘¢"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥æ¶ˆæ¯æ•°é‡æ’åç¬¬ä¸€"
type = ["send_message_top", "==", "1"]

[[badges]]
name = "ä¸æ‡ˆæ€ "
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥æ¶ˆæ¯æ•°é‡æ’åç¬¬äºŒ"
type = ["send_message_top", "==", "2"]

[[badges]]
name = "ä¹ç€å‘¢"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥è´´çº¸æ•°é‡æ’åç¬¬ä¸€"
type = ["send_sticker_top", "==", "1"]

[[badges]]
name = "æ°”æ°›ç»„"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥è´´çº¸æ•°é‡æ’åç¬¬äºŒ"
type = ["send_sticker_top", "==", "2"]

[[badges]]
name = "å›¾ç‹"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥å›¾ç‰‡æ•°é‡æ’åç¬¬ä¸€"
type = ["send_image_top", "==", "1"]

[[badges]]
name = "æ¬£èµæ´¾"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥å›¾ç‰‡æ•°é‡æ’åç¬¬äºŒ"
type = ["send_image_top", "==", "2"]
