[[badges]]
name = "æ´»ç€å‘¢"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥æ¶ˆæ¯æ•°é‡æ’åç¬¬ä¸€"
type = ["send_message_top", "==", "1"]

[[badges]]
name = "ä¹ç€å‘¢"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥è´´çº¸æ•°é‡æ’åç¬¬ä¸€"
type = ["send_sticker_top", "==", "1"]

[[badges]]
name = "å›¾ç‹"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥å›¾ç‰‡æ•°é‡æ’åç¬¬ä¸€"
type = ["send_image_top", "==", "1"]
