[[badges]]
name = "æ´»ç€å‘¢"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥æ¶ˆæ¯æ•°é‡æ’åç¬¬ä¸€"
type = ["send_message_top", "==", "1"]

[[badges]]
name = "ä¹ç€å‘¢"
emoji = "ğŸ˜¸"
description = "ä»Šæ—¥è´´çº¸æ•°é‡æ’åç¬¬ä¸€"
type = ["send_sticker_top", "==", "1"]