[[cards]]
name = "å“­è¯‰ 1"
emoji = "ğŸ“’"
description = "ä½¿æŸäººç¦è¨€ 1h"
point = 100

[[cards]]
name = "å“­è¯‰ 2"
emoji = "ğŸ“’"
description = "ä½¿æŸäººç¦è¨€ 3h"
point = 200

[[cards]]
name = "ç½®é¡¶"
emoji = "ğŸ”"
description = "å¯ç½®é¡¶ä¸€æ¡æ¶ˆæ¯"
point = 150

[[cards]]
name = "å¥–åŠ±"
emoji = "ğŸ–¼ï¸"
description = "ä»¤æŸäººå‘é€è‡ªå·±çš„ä¸€å¼ ç…§ç‰‡ï¼ˆéœ€åŒæ„ï¼Œä¸åŒæ„å°†è¿”è¿˜ï¼‰"
point = 200
